### ISSUE TITLE
Use `separator: '-'` instead

### ISSUE THREAD

**Issue by d4ins** [TheProfitCMS/the_string_to_slug#2]
It appears that you use old format of parameterize method.

Read this [http://stackoverflow.com/questions/14779879/prevent-change-of-one-field-in-rails-model](url). (this issue what I've encountered)

This deprecation was removed 10 days ago. https://github.com/rails/rails/commit/0189f4db6fe518de8909b66b7f30046bac52dedc

Try to fix it if you will have time.

**Comment by the-teacher** [comment]
👍 thanks! `v1.3` has been released

**Comment by d4ins** [comment]
Your welcome!

вт, 29 нояб. 2016 г. в 21:01, Ilya N. Zykin <notifications@github.com>:
